#!/bin/sh

# ipset-country (v20250721)
# =========================
#
# Block or allow countries using iptables, ipset and ipdeny.com
# Also works with ipverse.com and other providers

# INSTALLATION:
# -------------
# - Setup firewall if you have not done so yet, at least input chain is needed
# - Run this script from cron, e.g. /etc/cron.daily or systemd timer ('run pset-country -i')
# - To run on boot you can also add it to e.g. /etc/rc.local (or systemd)
# - Use argument "force" to load unchanged zonefiles instead of skipping

# NOTE: This script will add a adrop rule to your firewall
# make sure you do not lock yourself out in case of issues on a remote system

# CONFIGURATION:
# --------------
# OS: "auto", "manual", "debian", "suse" or "redhat" (default is auto)
# Example for OS="manual":  confdir="/etc/iptables"; rulesfile="${confdir}/myrules"

DISTRO="auto"

# Specify countries to block as 'ISOCODE,Name' (same as ipdeny.com)
# Multiple entries should be seperated by semicolon
# Example: "CN,China; US,United States; RU,Russia"

COUNTRY="CN,China; RU,Russia"

# ---[ FIREWALLS AND OPTIONS  ]-------------------------------------------------
#
# - Iptables (and ipset) is used to create the chains, rules and sets (default)
# - NFTables uses its own native sets instead of ipset
# - Firewalld can be set to use firewalld-cmd frontend
#     default is to use iptables-legacy
#     nftables as backend also works (translates '--ipset' to native nft sets)
# - UFW is an unsupported and untested frontend, but might work

FIREWALL="iptables" # Set to [iptables|ntftables|firewalld]

# To block specified Countries set MODE to "drop" (blacklist)
# To allow specified Countries and block all others, set MODE to "accept" (whitelist)

MODE="reject"       # Set target to use when ip matches country [accept|drop|reject])
LOGIPS=0            # Create logips chain to log matches [0/1]  (default=0)

# Iptables
RESTORE=0           # Run iptables-restore first, before adding rules [0/1] (default=0)
DENY_RULENUM=0      # Set to 0 to inject reject rule at end of rules (default)
                    # Set to 1 for beginning, or higher for specific rule number

# NFTables
NFT_RULE_LOC=""     # Set optional location specifier of an existing rule (default is "")
                    # Example: NFT_RULE_LOC="handle 3" or NFT_RULE_LOC="index 5"

# FirewallD
FIREWALLD_RH8=0     # Enable firewalld on CentOS/RHEL 8, at your own risk [0/1]

# ---[ BLOCK LIST PROVIDERS ]---------------------------------------------------
#
# IPdeny: "http://www.ipdeny.com/ipblocks/data/aggregated" (aggregated ipv4)
#         "http://www.ipdeny.com/ipv6/ipaddresses/blocks" (ipv6)
#         "http://www.ipdeny.com/ipblocks/data/countries" (full ipv4)
# IPverse: "https://github.com/ipverse/rir-ip"
# Others: should work if they offer (iso) country zonefiles with CIDR's
# Notes: - the "aggregated" zonefiles are smaller in size
#        - ipdeny has no md5sums for aggregated ipv6 zonefiles
#        - ipverse does not offer md5sums at all (this autosets MD5CHECK=0)

# Comment ipdeny lines and uncomment line below to use ipverse instead:
# IPBLOCK_URL="https://raw.githubusercontent.com/ipverse/rir-ip/refs/heads/master/country"

IPBLOCK_URL_V4="http://www.ipdeny.com/ipblocks/data/aggregated"
IPBLOCK_URL_V6="http://www.ipdeny.com/ipv6/ipaddresses/blocks"

# Use ipv4, ipv6 or both. (default: IPV4=1)
# For ipv6, set IPBLOCK_URL_V6 or the same url as ipv4 is used
IPV4=1
IPV6=0

MD5CHECK=1  # Check zonefile md5sums [0/1]  (default=1)
FORCE=0     # Run even if zonefile is unchanged [0/1]  (default=0)
            # same as running './ipset-country force'
FLUSH=0     # Flush set before adding zonefile [0/1]  (default=0)
            # this will take care of removed ranges

# Log to file e.g. "/path/to/my.log", screen "dev/stdout" or disable: "/dev/null 2>&1"
# Default is "/var/log/ipset-country.log"
LOG="/var/log/ipset-country.log"

# Level, see below and man syslog [0-7]  (default is 6=info)
# 0=emerg 1=alert crit=2 3=err 4=warning 5=notice 6=info 7=debug

LOGLVL=6

# END OF CONFIG
# -------------

scriptname="$( basename "$0" )"
basefile="$(basename -s '.sh' "$0")"

# arg '-c' config file
SAVE_IFS="$IFS"
IFS='|'
c=0
for i in "$@"; do
  if printf -- "%s" "$i" | grep -Eq -- "\-c"; then
    c=1
    continue
  else
    if [ "$c" -eq 1 ]; then
      if printf -- "%s" "$i" | grep -Eq -- "\-"; then
        echo "Error: config file not specfied, try \"$scriptname -h\""
        exit 1
      fi
      scriptconf="$i"
      if [ ! -s "$scriptconf" ]; then
        echo "Error: invalid config file \"$scriptconf\" specified"
        exit 1
      fi
      break
    fi
  fi
done
IFS="$SAVE_IFS"
# if scriptconf is empty, check for {/usr/local,}/etc/ipset-country.conf and in same dir as script
if [ -z "$scriptconf" ]; then
  sc="$(dirname "$0")/${basefile}.conf"
  for i in "/usr/local/etc/ipset-country.conf" "/etc/ipset-country.conf" "$sc"; do
    if [ -e "$i" ]; then
      scriptconf="$i"
      break
    fi
  done
fi
unset i
# make sure we dont source ourselves
if [ "$scriptconf" = "$0" ]; then
  echo "Error: invalid config file \"$scriptconf\" specified"
  exit 1
fi
# source scriptconf if its non empty, else exit
if [ -n "$scriptconf" ] && [ -s "$scriptconf" ]; then
  # shellcheck source=/usr/local/etc/ipset-country.conf disable=SC1091
  . "$scriptconf" || { echo "Error: could not load $scriptconf"; exit 1; }
fi

ipt_restore_run=0
ip6t_restore_run=0
ipt_logips_run=0
ip6t_logips_run=0

nl='
'
SAVE_LOG="$LOG"

func_msg() {
  msg="$*"; eol="$nl"; tee=0
  if echo "$msg" | grep -q '^m:'; then
    for i in "$@"; do
      # set output "mode"
      case $i in
        m:logfile) LOG="$SAVE_LOG" ;;
        m:stdout) tee=0; LOG="/dev/stdout";  ;;
        m:tee) tee=1 ;;
        m:nonl) eol=" " ;;
      esac
    done
    msg="$( echo "$msg" | sed -E 's/m:(nonl|stdout|tee) //g' )"
  fi
  if [ "$tee" -eq 1 ]; then
    printf "%s %s%s" "$( date +%F\ %T )" "$msg" "$eol" | tee -a "$LOG"
  else
    printf "%s %s%s" "$( date +%F\ %T )" "$msg" "$eol" >> "$LOG"
  fi
}

func_dist_auto() {
  if [ -s /etc/os-release ]; then
    if grep -iq "debian\\|ubuntu" /etc/os-release; then
      DISTRO="debian"
    elif grep -iq "centos\\|fedora\\|rhel" /etc/os-release; then
      DISTRO="redhat"
    elif grep -iq "suse" /etc/os-release; then
      DISTRO="suse"
    fi
  else
    [ -s /etc/debian_version ] && DISTRO="debian"
    [ -s /etc/redhat-release ] && DISTRO="redhat"
    [ -s /etc/SuSE-release ] && DISTRO="suse"
  fi
}

# set iptables and other vars
func_vars() {
  confdir="/etc"
  if [ "$proto" = "ipv6" ]; then
    ipt="ip6"
    ips_fam="inet6"
    nft_fam="ip6"
    rj_opt="icmp6-port-unreachable"
    case $DISTRO in
      debian)
        rulesfile="/etc/ip6tables.up.rules"
        [ -d "/etc/iptables" ] && confdir="/etc/iptables"
        [ -f "${confdir}/rules.v6" ] && rulesfile="${confdir}/rules.v6"
        ;;
      redhat|suse)
        confdir="/etc/sysconfig"
        rulesfile="${confdir}/ip6tables"
        ;;
    esac
  else
    ipt="ip"
    ips_fam="inet"
    nft_fam="ip"
    rj_opt="icmp-port-unreachable"
    case $DISTRO in
      debian)
        rulesfile="/etc/iptables.up.rules"
        [ -d "/etc/iptables" ] && confdir="/etc/iptables"
        [ -f "${confdir}/rules.v4" ] && rulesfile="${confdir}/rules.v4"
      ;;
      redhat|suse)
        confdir="/etc/sysconfig"
        rulesfile="${confdir}/iptables"
      ;;
    esac
  fi
  case $FIREWALL in
    iptables)
      frontend="${ipt}tables"
      if [ -x "/usr/sbin/${ipt}tables-legacy" ]; then
        iptables="/usr/sbin/${ipt}tables-legacy"
        iptrestore="/usr/sbin/${ipt}tables-legacy-restore"
        iptsave="/usr/sbin/${ipt}tables-legacy-save"
      else
        iptables="/sbin/${ipt}tables"
        iptrestore="/sbin/${ipt}tables-restore"
        iptsave="/sbin/${ipt}tables-save"
      fi
      if [ "$DISTRO" = "suse" ] ; then
        iptables="/usr${iptables}"
        iptrestore="/usr${iptrestore}"
        iptsave="/usr${iptsave}"
      fi
    ;;
    nftables)
      frontend="nft"
    ;;
    firewalld)
      frontend="firewalld-cmd"
    ;;
  esac
}

# download zonefile and get md5sum if enabled
func_zonefile() {
  zonefile="${cty_iso}.zone"
  if echo "$url" | grep -iq "ipdeny.com"; then
    if echo "$url" | grep -q "aggregated"; then
      zonefile="${cty_iso}-aggregated.zone"
      if [ "$proto" = "ipv6" ]; then
        MD5CHECK=0
      fi
    fi
  fi
  zoneurl="$zonefile"
  if echo "$url" | grep -iq "/ipverse"; then
    MD5CHECK=0
    zoneurl="${cty_iso}/${proto}-aggregated.txt"
  fi
  $getfile "/tmp/${proto}-${zonefile}.$$" "${url}/${zoneurl}"
  # check downloaded zonefile against MD5SUM
  if [ "$MD5CHECK" -eq 1 ]; then
    md5src="$( $getfile - "$url/MD5SUM" | grep "$zonefile" | cut -d" " -f 1 )"
  fi
  # check if zonefile is the same as current
  md5chk="$( md5sum "/tmp/${proto}-${zonefile}.$$" | cut -d" " -f 1 )"
  if [ -f "${confdir}/${proto}-${zonefile}" ]; then
    md5cur="$( md5sum "${confdir}/${proto}-${zonefile}" 2>/dev/null | cut -d" " -f 1 )"
    if [ -z "$md5cur" ] || [ "$md5cur" = "" ]; then
       zf_res="NOK: md5"
    fi
  fi
  if [ "$md5cur" != "$md5chk" ]; then
    mv "/tmp/${proto}-${zonefile}.$$" "${confdir}/${proto}-${zonefile}" && \
      zf_res="OK" || zf_res="NOK"
  else
    if [ "$FORCE" -ne 1 ]; then zf_res="SKIP"; else zf_res="FORCE"; fi
  fi
  func_msg "zonefile: get \"${proto}-${zonefile}\" - $zf_res"
}

# restore iptables, once
func_ipt_restore() {
  if { [ "$proto" = "ipv4" ] && [ "$ipt_restore_run" -ne 1 ]; } ||
     { [ "$proto" = "ipv6" ] && [ "$ip6t_restore_run" -ne 1 ]; }
  then
    $iptrestore < "$rulesfile" && ipt_restore="OK" || ipt_restore="NOK"
    func_msg "$frontend: restore - $ipt_restore"
    [ "$proto" = "ipv4" ] && ipt_restore_run=1
    [ "$proto" = "ipv6" ] && ip6t_restore_run=1
  fi
}

# check if logips chain and rules already exist, else create them - once
func_ipt_log() {
  ipt_exists=0
  if { [ "$proto" = "ipv4" ] && [ "$ipt_logips_run" -ne 1 ]; } ||
     { [ "$proto" = "ipv6" ] && [ "$ip6t_logips_run" -ne 1 ]; }
  then
    if ! $iptsave | grep -q "LOGIPS"; then
      $iptables -N LOGIPS && ipt_chain="OK" || ipt_chain="NOK"
    else
      ipt_chain="already exists"
    fi
    if ! $iptsave | grep -q "LOGIPS.*LOG"; then
      $iptables -A LOGIPS -m limit --limit 10/min -j LOG --log-prefix "IPS: " --log-level $LOGLVL && \
        ipt_append="OK" || ipt_append="NOK"
    else
      ipt_append="already exists"
    fi
    case "$MODE" in
      accept)
        if ! $iptsave | grep -q "LOGIPS.*REJECT"; then
          if ! $iptsave | grep -q "LOGIPS.*DROP"; then
            if ! $iptsave | grep -q "LOGIPS.*ACCEPT"; then
              $iptables -A LOGIPS -j ACCEPT && ipt_target="OK" || ipt_target="NOK"
            else ipt_target="ACCEPT already exists"; fi
          else ipt_target="DROP already exists, remove it first"; ipt_exists=1; fi
        else ipt_target="REJECT already exists, remove it first"; ipt_exists=1; fi
      ;;
      drop)
        if ! $iptsave | grep -q "LOGIPS.*REJECT"; then
          if ! $iptsave | grep -q "LOGIPS.*DROP"; then
            $iptables -A LOGIPS -j DROP && ipt_target="OK" || ipt_target="NOK"
          else ipt_target="DROP already exists"; fi
        else ipt_target="REJECT already exists, remove it first"; ipt_exists=1; fi
      ;;
      reject|*)
        if ! $iptsave | grep -q "LOGIPS.*DROP"; then
          if ! $iptsave | grep -q "LOGIPS.*REJECT"; then
            $iptables -A LOGIPS -j REJECT --reject-with "$rj_opt" && ipt_target="OK" || ipt_target="NOK"
          else ipt_target="REJECT already exists"; fi
        else ipt_target="DROP already exists, remove it first"; ipt_exists=1; fi
      ;;
    esac
    func_msg "$frontend: create log chain - $ipt_chain"
    func_msg "$frontend: append log rule - $ipt_append"
    func_msg "$frontend: append $MODE rule - $ipt_target"
    [ "$ipt_exists" -ne 0 ] && { func_msg m:stdout "exiting..."; exit 1; }
    [ "$proto" = "ipv4" ] && ipt_logips_run=1
    [ "$proto" = "ipv6" ] && ip6t_logips_run=1
  fi
}

func_ipt_deny() {
  # if DENY_RULENUM is:
  #   0:  inject rule at end
  #   1:  inject rule at start
  #   >1: add rule at specified <rulenum>
  rulenum=0
  if [ "${DENY_RULENUM:-0}" -eq 0 ]; then
    rulenum=$(( $(${iptables} -S INPUT 2>/dev/null|wc -l) - 1 )) || rulenum=1
  else
     rulenum=$DENY_RULENUM
  fi
  # alternative method, slower:
  #   rulenum="$(( $(${iptables} -L INPUT --line-numbers | tail -1 | awk '{print $1}') - 1 ))"
  [ "$rulenum" -eq 0 ] && rulenum=1
  if $iptsave | grep -q "match-set.*${proto}-${cty_name}.*LOGIPS"; then
    ipt_set="already exists"
  else
    $iptables -I INPUT "$rulenum" -p tcp -m set --match-set "${proto}-${cty_name}" src -j LOGIPS >/dev/null 2>&1 && \
      ipt_set="OK" || ipt_set="NOK"
  fi
  # if logips chain does not exist - because logips=0 or previous cmds failed - insert ipset block rule
  if ! $iptsave | grep -q "\\-A LOGIPS" || test $LOGIPS -eq 0; then
    if [ "$MODE" = "reject" ]; then
      # also check if ipset rule doesnt exist
      if $iptsave | grep -q "match-set.*${proto}-${cty_name}.*REJECT"; then
        ipt_set="already exists"
      else
        $iptables -I INPUT "$rulenum" -p tcp -m set --match-set "${proto}-${cty_name}" src -j REJECT --reject-with "$rj_opt" && \
          ipt_set="OK" || ipt_set="NOK"
      fi
    elif [ "$MODE" = "drop" ]; then
      if $iptsave | grep -q "match-set.*${proto}-${cty_name}.*DROP"; then
        ipt_set="already exists"
      else
        $iptables -I INPUT "$rulenum" -p tcp -m set --match-set "${proto}-${cty_name}" src -j DROP && \
          ipt_set="OK" || ipt_set="NOK"
      fi
    fi
  fi
  func_msg "$frontend: insert ipset deny rule - $ipt_set"
}

# add ipset allow rule
func_ipt_allow() {
  rulenum=1
  if ! $iptsave | grep -q "match-set.*${proto}-${cty_name}.*LOGIPS"; then
    $iptables -I INPUT "$rulenum" -p tcp -m set --match-set "${proto}-${cty_name}" src -j LOGIPS >/dev/null 2>&1 && \
      ipt_set="OK" || ipt_set="NOK"
  else
    ipt_set="already exists"
  fi
  # if logips chain does not exist - because logips=0 or previous cmds failed - insert ipset block rule
  if ! $iptsave | grep -q "\\-A LOGIPS" || test $LOGIPS -eq 0; then
    if $iptsave | grep -q "match-set.*${proto}-${cty_name}.*ACCEPT"; then
      ipt_set="already exists"
    else
      $iptables -I INPUT "$rulenum" -p tcp -m set --match-set "${proto}-${cty_name}" src -j ACCEPT && \
        ipt_set="OK" || ipt_set="NOK"
    fi
  fi
  func_msg "$frontend: insert ipset allow rule - $ipt_set"
}

# create ipset using type hash
func_ips_create() {
  ips_create="NOK"
  if ! ipset list -terse "${proto}-${cty_name}" >/dev/null 2>&1; then
    if ipset create "${proto}-${cty_name}" hash:net family ${ips_fam}; then
      ips_create="OK"
    fi
  else
    ips_create="OK"
  fi
  func_msg "ipset: create set \"${proto}-$cty_name\" - $ips_create"
}

# add blocks to ipset
func_ips_add() {
  if [ "${FLUSH:-0}" -eq 1 ]; then
    ipset flush "${proto}-${cty_name}"
  fi
  i=0; while read -r cidr; do
    if ipset add -exist -quiet "${proto}-${cty_name}" "$cidr"; then
      i=$((i+1))
    else
      echo "NOK: \"${proto}-${cty_name}\" - $i - $cidr"
    fi
  done < "${confdir}/${proto}-${zonefile}" >/dev/null 2>&1 && ips_add="OK" || ips_add="NOK"
  [ "$i" -eq 0 ] && ips_add="NOK"
  func_msg "ipset: add \"${proto}-${zonefile}\" to set \"${proto}-${cty_name}\" - $ips_add - $i entries"
}

func_firewalld_ips() {
  if ! $firewall_cmd --get-ipsets | grep -q "${proto}-${cty_name}"; then
    func_msg m:nonl "$frontend: new ipset \"${proto}-${cty_name}\" -"
    $firewall_cmd --permanent --new-ipset="${proto}-${cty_name}" --type=hash:net --option=family="${ips_fam}" >>"$LOG" 2>&1
  fi
  func_msg m:nonl "$frontend: add to ipset -"
  $firewall_cmd --permanent --ipset="${proto}-${cty_name}" --add-entries-from-file="${confdir}/${proto}-${zonefile}" >>"$LOG" 2>&1 && { \
    i="$( ipset -terse list "${proto}-${cty_name}" | awk 'END { print $NF }' )"
    func_msg "ipset: add \"${proto}-${zonefile}\" to \"${proto}-${cty_name}\" - $i entries"
  }
}

# drop: All incoming connections are rejected. Outbound connections are possible.
func_firewalld_drop() {
  if ! $firewall_cmd --zone=drop --list-sources | grep -q "${proto}-${cty_name}"; then
    func_msg m:nonl m:tee "$frontend: add source to drop zone -"
    { $firewall_cmd --permanent --zone=drop --add-source="ipset:${proto}-${cty_name}" && echo; } >>"$LOG" 2>&1
  fi
}

# public: Use this zone for public environments in which you do not trust other computers on the network. Only predefined connections (i.e. ports / services) are accepted.f
unc_firewalld_public() {
  if ! $firewall_cmd --zone=public --list-sources | grep -q "${proto}-${cty_name}"; then
    func_msg m:nonl m:tee "$frontend: add source to public zone -"
    { $firewall_cmd --permanent --zone=public --add-source="ipset:${proto}-${cty_name}" && echo; } >>"$LOG" 2>&1
  fi
}

func_nft_set() {
  if ! nft list set $nft_fam filter "${proto}-${cty_name}" >/dev/null 2>&1; then
    if ! nft add set $nft_fam filter "${proto}-${cty_name}" \{ type "${proto}_addr"\; size 65536\; flags interval\; \} >>"$LOG" 2>&1; then
      func_msg "nft: add set \"${proto}-$cty_name\" - NOK. Exiting ..."
      exit 1
    fi
  fi
  func_msg "nft: add set \"${proto}-$cty_name\" - OK"
}

func_nft_add() {
  if [ "${FLUSH:-0}" -eq 1 ]; then
    nft flush set $nft_fam filter "${proto}-${cty_name}"
  fi
  i=0; while read -r cidr; do
    if nft add element $nft_fam filter "${proto}-${cty_name}" \{ "$cidr" \} >>"$LOG" 2>&1; then
      i=$((i+1))
    else
      echo "NOK: \"${proto}-${cty_name}\" - $i - $cidr"
    fi
  done < "${confdir}/${proto}-${zonefile}" >/dev/null 2>&1 && nft_add="OK" || nft_add="NOK"
  [ "$i" -eq 0 ] && nft_add="NOK"
  func_msg "nft: add \"${proto}-${zonefile}\" to set \"${proto}-${cty_name}\" - $nft_add - $i elements"
}

func_nft_rule() {
  nft_rule="NOK"
  if ! nft list chain $nft_fam filter input | grep -Eq "@${proto}-${cty_name}.*$MODE"; then
    # shellcheck disable=SC2086
    if nft add rule $nft_fam filter input ${NFT_RULE_LOC} $nft_fam saddr "@${proto}-${cty_name}" $MODE >>"$LOG"; then
      nft_rule="OK"
    fi
  else
    nft_rule="OK"
  fi  
  func_msg "nft: add rule \"${proto}-$cty_name\" $MODE - $nft_rule"
}

func_nft_log() {
  nft_log="NOK"
  mode_uc="$(echo $MODE | tr '[:lower:]' '[:upper:]')"
  if ! nft list chain $nft_fam filter input | grep -Eq "log prefix \"NFT: $mode_uc"; then
    if nft add rule $nft_fam filter input limit rate 10/minute burst 5 packets counter log prefix \"NFT: "$mode_uc" \" >>"$LOG"; then
      nft_log="OK"
    fi
  else
    nft_log="OK"
  fi
  func_msg "nft: add log $MODE - $nft_log"
}

# arg "-i" installs systemd service
if printf -- "%s" "$*" | grep -Eq -- "\-i"; then
  if [ ! -d /run/systemd/system ]; then
    echo "ERROR: systemd not found"
    exit 1
  fi
  if [ -e /lib/systemd/system/ipset-country.service ]; then
    echo "ERROR: systemd service already exists"
    exit 1
  fi
  cat <<-_EOF_ > /lib/systemd/system/ipset-country.service
[Unit]
Description=ipset-country

[Service]
Type=oneshot
ExecStart=$(dirname "$(readlink -f "$0")")/$scriptname
StandardError=file:/var/log/ipset-country.err
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
_EOF_
  cat <<-_EOF_ > /lib/systemd/system/ipset-country.timer
Description=ipset-country daily timer

[Timer]
OnBootSec=2min
OnCalendar=daily

[Install]
WantedBy=timers.target
_EOF_
  if systemctl daemon-reload; then
    if systemctl enable --now ipset-country.timer; then
      echo "Systemd service and timer 'ipset-country' installed"
    else
      echo "ERROR: could not start systemd timer"
      exit 1
    fi
  fi
  exit
fi

# arg "-u" uninstalls systemd service
if printf -- "%s" "$*" | grep -Eq -- "\-u"; then
  systemctl stop ipset-country
  systemctl stop ipset-country.timer
  systemctl disable ipset-country
  systemctl disable ipset-country.timer
  rm /lib/systemd/system/ipset-country.service
  rm /lib/systemd/system/ipset-country.timer
  systemctl daemon-reload
  systemctl reset-failed
  exit
fi

# preflight checks

if printf -- "%s" "$*" | grep -Eq -- "\-h|help"; then
  echo""
  echo "./$scriptname [-c </path/to/conf>|-i|-u|-f]"
  echo
  echo "  -c  specify config file"
  echo "  -i  install systemd service and timer"
  echo "  -u  uninstall from systemd"
  echo "  -f  force loading unchanged zonefiles"
  echo
  echo "See comments in script and README.md for details"
  echo
  exit 0
fi
if [ "$( id -u )" -ne 0 ]; then
  echo "Script \"$scriptname\" needs root to run"
  exit 1
fi
if [ "${UFW:-0}" -ne 1 ]; then
  if which ufw >/dev/null 2>&1; then
    if ufw status | grep -q "Status: active"; then
      echo "UFW is not supported, disable it first (or set UFW=\"1\")"
      exit 1
    fi
  fi
fi
if printf -- "%s" "$*" | grep -Eiq -- "\-f|force"; then
  FORCE=1
fi
if [ ! -w "$( dirname "$LOG" )" ]; then
  echo "Log \"$LOG\" not writable, using \"/tmp/${basefile}.log\" instead"
  LOG="/tmp/${basefile}.log"
fi
if printf -- "%s" "$*" | grep -Eiq -- "debug"; then
  LOG=/dev/stdout
fi

[ "$DISTRO" = "auto" ] && func_dist_auto
func_vars

if ! echo "$FIREWALL" | grep -Eq "iptables|nftables|firewalld|ufw" ; then
  echo "invalid FIREWALL setting"
  exit 1
fi

if ! echo "$MODE" | grep -Eq "accept|drop|reject" ; then
  echo "invalid MODE setting"
  exit 1
fi

case $FIREWALL in
  iptables)
    if [ -x "$iptables" ]; then
      ipt_cmd="OK"
    else
      ipt_cmd="NOK. iptables not found."
    fi
    if $iptables -n -L INPUT >/dev/null 2>&1; then
      ipt_chain="OK"
    else
      ipt_chain="NOK. INPUT chain not found."
    fi
    if [ -d "$confdir" ];  then
      ipt_dir="OK"
    else
      ipt_dir="NOK. Config dir not found."
    fi
    if [ "$ipt_cmd" != "OK" ] || [ "$ipt_chain" != "OK" ];then
      func_msg m:tee "$frontend: $iptables ${ipt_cmd}, input chain: $ipt_chain"
    fi
    if [ "$ipt_dir" != "OK" ];then
      func_msg m:tee "$frontend: confdir $confdir - $ipt_dir"
    fi
    if [ "$ipt_cmd" != "OK" ] || [ "$ipt_chain" != "OK" ] || [ "$ipt_dir" != "OK" ]; then
      func_msg m:tee "exiting..."
      exit 1
    fi
    ipset="$( which ipset 2>/dev/null )"
    if [ -x  "$ipset" ]; then
      ips_cmd="OK"
    else
      ips_cmd="NOK. ipset not found."
    fi
    if [ "$ips_cmd" != "OK" ]; then
      func_msg m:tee "ipset: $ips_cmd, exiting..."
      exit 1
    fi
    if [ "$RESTORE" -eq 1 ] && [ ! -f "$rulesfile" ]; then
      func_msg m:stdout "could not find iptables rules file \"${rulesfile}\""
      exit 1
    fi
  ;;
  nftables)
    nft_cmd="$( which nft 2>/dev/null )"
    if [ -x "$nft_cmd" ]; then
        func_msg "nftables: $frontend - OK"
    else
        func_msg "nftables: $frontend - NOK. nft not found, exiting..."
        exit 1
    fi
    if ! nft list chain $nft_fam filter input >/dev/null 2>&1; then
        func_msg "nftables: $frontend - NOK. input chain not found, exiting..."
        exit 1
    fi
  ;;
  firewalld)
    if [ "$DISTRO" = "redhat" ] && [ "$FIREWALLD_RH8" -ne 1 ]; then
      if grep -Eiq "red hat enterprise linux 8.0|centos linux 8" /etc/os-release; then
        echo
        echo "WARNING: There are issues with firewalld and nftables on CentOS/RHEL 8 which"
        echo "         can cause your firewall to break resulting in being locked out."
        echo "         Adding large ipsets apparently can takes a VERY long time. To abort, you"
        echo "         need remote console access and run 'pkill firewal-cmd; nft flush ruleset'"
        echo "         Set FIREWALLD_RH8=1 to disable this message"
        echo
        printf "Press any key to quit or 'Y' then [ENTER] to continue "
        read -r a
        if ! echo "$a" | grep -iq y;
          then exit 1
        fi
        FIREWALLD_RH8=1
        func_msg m:stdout "continuing..."
      fi
    fi
    firewall_cmd="$( which firewall-cmd 2>/dev/null )"
    if [ -x "$firewall_cmd" ]; then
      func_msg "firewalld: $frontend - OK"
    else
      func_msg "firewalld: $frontend - NOK. Command not found, exiting..."
      exit 1
    fi
    if [ "$MODE" = "reject" ]; then
      func_msg "firewalld: MODE=\"reject\" not suppported, using 'drop' instead"
    fi
    if [ "${LOGIPS:-0}" = 1 ]; then
      func_msg "firewalld: LOGIPS=1 not suppported, igored"
    fi
  ;;
esac

{ getfile=$( which wget 2>/dev/null ) && getfile="$getfile -q -O"; }
if [ -z "$getfile" ]; then
  func_msg m:stdout "curl or wget not found, exiting..."
  exit 1
fi
if ! which md5sum >/dev/null 2>&1; then
  func_msg m:stdout "md5sum not found, exiting..."
  exit 1
fi

# main loop: handle country here
func_block_ip() {
  SAVE_IFS="$IFS"
  IFS=";"
  for cty in $COUNTRY; do
    cty="$( echo "$cty" | tr '[:upper:]' '[:lower:]' )"
    cty_iso="$( echo "$cty" | cut -d',' -f 1 | sed -r -e 's/(^ +| +$)//g' )"
    cty_name="$( echo "$cty" | cut -d',' -f 2 | sed -r -e 's/(^ +| +$)//g' -e 's/ /_/g' )"
    if [ "$cty_name" != "" ]; then
      IFS="$SAVE_IFS"
      for url in $1; do
        # change protocol if its an ipv6 zonefile url
        if echo "$url" | grep -q "ipv6"; then
          proto="ipv6"
        fi
        func_vars
        func_zonefile
        if [ "$MD5CHECK" -eq 0 ] || [ "$md5src" = "$md5chk" ]; then
          if [ "$zf_res" = "SKIP" ]; then
            continue
          fi
          case $FIREWALL in
            iptables)
              func_ips_create
              if [ "${RESTORE:-0}" -eq 1 ]; then
                func_ipt_restore
              fi
              if [ "${LOGIPS:-0}" -eq 1 ]; then
                func_ipt_log
              fi
              func_ips_add
              if [ "${MODE:-drop}" = "accept" ]; then
                func_ipt_allow  # whitelist
              else
                func_ipt_deny  # blacklist
              fi
            ;;
            nftables)
              func_nft_set
              func_nft_add
              func_nft_rule
              if [ "${LOGIPS:-0}" -eq 1 ]; then
                func_nft_log
              fi
            ;;
            firewalld)
              func_firewalld_ips
              if [ "${MODE:-drop}" = "accept" ]; then
                func_firewalld_drop  # whitelist
              else
                func_firewalld_public  # blacklist
              fi
            ;;
          esac
        else
          func_msg "zonefile: md5 \"${proto}-${zonefile}\" mismatch\""
        fi
      done
    else
      func_msg m:stdout "incorrect country setting\""
    fi
    if [ -f "/tmp/${proto}-${zonefile}.$$" ]; then
      rm "/tmp/${proto}-${zonefile}.$$"
    fi
  done
}

if [ "$IPV4" -eq 1 ]; then
  proto="ipv4"
  if [ -z "$IPBLOCK_URL_V4" ]; then
    IPBLOCK_URL_V4="$IPBLOCK_URL"
  fi
  func_block_ip "$IPBLOCK_URL_V4"
fi

# ipv6 uses /sbin/ip6tables
if [ "$IPV6" -eq 1 ]; then
  proto="ipv6"
  if [ -z "$IPBLOCK_URL_V6" ]; then
    IPBLOCK_URL_V6="$IPBLOCK_URL"
  fi
  if [ -z "$IPBLOCK_URL_V6" ] && [ -z "$IPBLOCK_URL" ]; then
    IPBLOCK_URL_V6="$IPBLOCK_URL_V4"
  fi
  func_block_ip "$IPBLOCK_URL_V6"
fi

case $FIREWALL in
  iptables)
    if ${iptsave} | ${iptrestore} --test; then
      func_msg m:tee "iptables: test ruleset - OK"
    else
      func_msg m:tee "iptables: test ruleset - FAILED. Exiting..."
      exit 1
    fi
  ;;
  nftables)
    #nft -c list ruleset
    true
  ;;
  firewalld)
    func_msg m:nonl m:stdout "firewalld: reload -"
    $firewall_cmd --reload >>"$LOG" 2>&1
  ;;
esac

func_msg m:stdout "ipset-country: done"
IFS="$SAVE_IFS"
